apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{SERVICE_ACCOUNT}}
  namespace: {{NAMESPACE}}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: snapshot-role
  namespace: {{NAMESPACE}}
rules:
  - apiGroups: ["snapshot.kubevirt.io"]
    resources: ["virtualmachinesnapshots"]
    verbs: ["create", "delete", "list", "get"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list"]
  - apiGroups: ["kubevirt.io"]
    resources: ["virtualmachines"]
    verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: snapshot-rolebinding
  namespace: {{NAMESPACE}}
subjects:
  - kind: ServiceAccount
    name: {{SERVICE_ACCOUNT}}
    namespace: {{NAMESPACE}}
roleRef:
  kind: Role
  name: snapshot-role
  apiGroup: rbac.authorization.k8s.io
